spring.application.name=github.events

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# JPA
spring.jpa.hibernate.ddl-auto=validate

# Scheduling
spring.threads.scheduled.pool.size=2

# GitHub
github.events.url=https://api.github.com/events

# Docker Compose support (disabled when running in container)
spring.docker.compose.enabled=false
